// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiEFDBF.Models;

#nullable disable

namespace WebApiEFDBF.Migrations
{
    [DbContext(typeof(FacturacionDBContext))]
    [Migration("20250919041824_cascadefacdetails")]
    partial class cascadefacdetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiEFDBF.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_articulo");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("WebApiEFDBF.Models.DetallesFactura", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdArticulo")
                        .HasColumnType("int")
                        .HasColumnName("id_articulo");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("IdDetalle")
                        .HasName("pk_detalle_factura");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdFactura");

                    b.ToTable("Detalles_factura", (string)null);
                });

            modelBuilder.Entity("WebApiEFDBF.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("Cliente")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cliente");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<int?>("NroFactura")
                        .HasColumnType("int")
                        .HasColumnName("nro_factura");

                    b.HasKey("IdFactura")
                        .HasName("pk_factura");

                    b.HasIndex("IdPago");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("WebApiEFDBF.Models.FormaPago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("FormaPago1")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("forma_pago");

                    b.HasKey("IdPago")
                        .HasName("pk_forma_pago");

                    b.ToTable("forma_pago", (string)null);
                });

            modelBuilder.Entity("WebApiEFDBF.Models.DetallesFactura", b =>
                {
                    b.HasOne("WebApiEFDBF.Models.Articulo", "IdArticuloNavigation")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("IdArticulo")
                        .HasConstraintName("fk_detalle_articulo");

                    b.HasOne("WebApiEFDBF.Models.Factura", "IdFacturaNavigation")
                        .WithMany("DetallesFacturas")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_detalle_factura_factura");

                    b.Navigation("IdArticuloNavigation");

                    b.Navigation("IdFacturaNavigation");
                });

            modelBuilder.Entity("WebApiEFDBF.Models.Factura", b =>
                {
                    b.HasOne("WebApiEFDBF.Models.FormaPago", "IdPagoNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdPago")
                        .HasConstraintName("fk_factura_forma_pago");

                    b.Navigation("IdPagoNavigation");
                });

            modelBuilder.Entity("WebApiEFDBF.Models.Articulo", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("WebApiEFDBF.Models.Factura", b =>
                {
                    b.Navigation("DetallesFacturas");
                });

            modelBuilder.Entity("WebApiEFDBF.Models.FormaPago", b =>
                {
                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
