// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiEFDBF.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public int? NroFactura { get; set; }

    public DateTime? Fecha { get; set; }

    public int? IdPago { get; set; }

    public string Cliente { get; set; }

    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();

    public virtual FormaPago IdPagoNavigation { get; set; }
}